// Code generated by ent, DO NOT EDIT.

package guild

const (
	// Label holds the string label denoting the guild type in the database.
	Label = "guild"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBotPrefix holds the string denoting the bot_prefix field in the database.
	FieldBotPrefix = "bot_prefix"
	// Table holds the table name of the guild in the database.
	Table = "guilds"
)

// Columns holds all SQL columns for guild fields.
var Columns = []string{
	FieldID,
	FieldBotPrefix,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBotPrefix holds the default value on creation for the "bot_prefix" field.
	DefaultBotPrefix string
	// BotPrefixValidator is a validator for the "bot_prefix" field. It is called by the builders before save.
	BotPrefixValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)
